desktop-image: "background.png"
desktop-image-scale-method: "crop"

title-text: " "

message-font: "${FONT_NAME} ${FONT_STYLE} ${FONT_SIZE_LARGER}"

terminal-font: "${FONT_NAME} ${FONT_STYLE} ${FONT_SIZE_SMALLER}"
terminal-box: "terminal_box_*.png"
terminal-left: "${TERMINAL_LEFT}"
terminal-width: "${TERMINAL_WIDTH}"
terminal-top: "${TERMINAL_TOP}"
terminal-height: "${TERMINAL_HEIGHT}"
terminal-border: "0"

+ image {
  left = 0
  width = ${TITLE_WIDTH}
  top = ${TITLE_TOP}
  height = ${TITLE_HEIGHT}

  file = "title.png"
}

+ label {
  left = ${TIMEOUT_LEFT}
  top = ${TIMEOUT_TOP}
  align = "center"
  id = "__timeout__"
  
  font = "${FONT_NAME} ${FONT_STYLE} ${FONT_SIZE_LARGER}"
  text = "${TIMEOUT_TEXT}"
  color = "#777777"
}

+ boot_menu {
  # location & size
  left = 0
  width = ${BOOT_MENU_WIDTH}
  top = ${BOOT_MENU_TOP}
  height = ${BOOT_MENU_HEIGHT}

  # icons
  icon_width = ${ICON_SIZE}
  icon_height = ${ICON_SIZE}

  # all items
  item_height = ${ITEM_HEIGHT}
  item_padding = 0
  item_icon_space = ${ITEM_ICON_SPACE}
  item_spacing = ${ITEM_SPACING}

  # unselected items
  item_color = "${ITEM_COLOR_HEX}"
  item_font = "${FONT_NAME} ${FONT_STYLE} ${FONT_SIZE_LARGER}"
  item_pixmap_style = "item_*.png"

  # selected items
  selected_item_color = "#926453"
  selected_item_font = "${FONT_NAME} ${FONT_STYLE} ${FONT_SIZE_LARGER}"
  selected_item_pixmap_style = "selected_item_*.png"
}